# Site settings
title: "About ME (Shunchen Shi)"
description: "A resume for ShiShunchen."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shunchen Shi"
resume_title:                   "Computer Architecture, Processing in Memory"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lisasimpson@youremailaddress.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_wechat:          "ssc4671627"
resume_contact_address:         "No.6 Kexueyuan South Road Zhongguancun,Haidian District Beijing, China"

resume_header_contact_info:     "No.6 Kexueyuan South Road Zhongguancun,Haidian District Beijing, China"
display_header_contact_info:    "ture"

resume_header_intro: "<p>I am Shunchen Shi (史舜晨), a 3rd year PhD student at ICT, CAS, advised by Prof.Ninghui Sun and Prof. Xueqi Li.
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        true
resume_section_recognition:     true
resume_section_skills:          true
# resume_section_associations:    true
resume_section_interests:       true
resume_section_links:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/shunchen_shi/profilecard/?igsh=MWJhYWtsdHhyb2szYw=="
  # resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
